### ISSUE TITLE
Update /join.md to reflect current status, and check if the link is still alive.

### ISSUE THREAD

**Issue by medicalwei** [lxde/beta.lxde.org#1]
The /join.md is majorly scrapped from <http://lxde.org/join_lxde_community> and an update is needed for the new site. Mainly:

- Where is our bugtracker now? On GitHub or Sourceforge?
- Are we still using mailing lists on Sourceforge?
- Do we still operate social network pages, if so, what services should we list?
- Do we still accept donations to LXDE Foundation e.V.?

**Comment by LStranger** [comment]
>- Where is our bugtracker now? On GitHub or Sourceforge?

For GTK+ only stuff it's still sourceforge, for rest it's github.

>- Are we still using mailing lists on Sourceforge?

All mailing lists are still active there.

>- Do we still operate social network pages, if so, what services should we list?

Correct me if I'm wrong but only active social page was forum.lxde.org.
Other services should be still active except Pootle which needs a fix.

>- Do we still accept donations to LXDE Foundation e.V.?

Did it ever work at all?
